# делаем образ контейнера с нуля
FROM scratch

# Добавляем минимальную Ubuntu
ADD ubuntu-24.04-minimal-cloudimg-amd64-root.tar.xz /

# настраиваем окружение
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Устанавливаем nginx, после установки чистим кэш, удаляем ненужные файлы
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
            nginx \
            iputils-ping && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Копируем конфиг Nginx
COPY conf.d/default.conf /etc/nginx/conf.d/default.conf

# Создаём пользователя и директории ДО установки пакетов
RUN adduser --system --no-create-home --group nginx && \
    mkdir -p /var/www/html /var/log/nginx /run/nginx && \
    chown -R nginx:nginx /var/www/html /var/log/nginx /run/nginx /var/lib/nginx

# Даём ping возможность работать от любого пользователя
RUN chmod u+s /bin/ping

# Настраиваем nginx на работу от пользователя nginx
RUN sed -i '/^user www-data;/d' /etc/nginx/nginx.conf

# Меняем путь к pid файлу (чтобы он был внутри директории /run/nginx)
RUN sed -i 's|/run/nginx.pid|/run/nginx/nginx.pid|' /etc/nginx/nginx.conf

# устанавливаем права на директории
RUN chmod 755 /var/www/html /var/log/nginx /run/nginx

# Том для данных - файлы сайта
#VOLUME /var/www/html

# веб-интерфейс
EXPOSE 80

# меняем пользователя на nginx
USER nginx

# Запускаем nginx от имени пользователя nginx
CMD ["nginx", "-g", "daemon off;"]
