server {
    listen 80;
    server_name localhost;

    # Главная страница идёт в Python
    location / {
        proxy_pass http://python:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Прокси в Python для остальных маршрутов
    location /ping {
        proxy_pass http://python:5000/ping;
        proxy_set_header Host $host;
    }

    location /hello {
        proxy_pass http://python:5000/hello;
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://python:5000/api/;
        proxy_set_header Host $host;
    }
}